[build-system]
requires = ["hatchling>=1.32"]
build-backend = "hatchling.build"

[project]
name = "ollama-response-generator-tayra"
dynamic = ["version"]
description = 'A response generator run with Ollama and ChromaDb.'
readme = "README.md"
requires-python = ">=3.12"
license = "AGPL-3.0-or-later"
keywords = [
  "generative ai",
  "ollama",
  "ai",
  "chromadb",
]
authors = [
  { name = "Tayra Sakurai", email = "tayra_sakurai@icloud.com" },
]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Programming Language :: Python :: Implementation :: CPython",
]
dependencies = [
  "langchain>=1.4",
  "Django>=6.1",
  "pydantic>=2.13",
  "langchain-ollama>=1.1",
  "langchain-chroma>=1.1",
  "langchain-text-splitters>=1.1",
]

[project.optional-dependencies]
dev = [
  "Sphinx>=9.1",
  "pytest>=9.1",
  "hatch>=1.18",
]

[project.urls]
Documentation = "https://github.com/Tayra-Sakurai/ollama-response-generator-tayra#readme"
Issues = "https://github.com/Tayra-Sakurai/ollama-response-generator-tayra/issues"
Source = "https://github.com/Tayra-Sakurai/ollama-response-generator-tayra"

[tool.hatch.version]
path = "src/ollama_response_generator_tayra/__about__.py"

[tool.hatch.envs.types]
extra-dependencies = [
  "mypy>=1.0.0",
]
[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/ollama_response_generator_tayra tests}"

[tool.coverage.run]
source_pkgs = ["ollama_response_generator_tayra", "tests"]
branch = true
parallel = true
omit = [
  "src/ollama_response_generator_tayra/__about__.py",
]

[[tool.hatch.envs.hatch-test.matrix]]
python = ["3.14", "3.13", "3.12"]

[tool.coverage.paths]
ollama_response_generator_tayra = ["src/ollama_response_generator_tayra", "*/ollama-response-generator-tayra/src/ollama_response_generator_tayra"]
tests = ["tests", "*/ollama-response-generator-tayra/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]

[tool.uv.workspace]
members = [
    ".",
    ".",
    ".",
    ".",
    ".",
    ".",
    ".",
    ".",
    ".",
]

[tool.uv.sources]
ollama-response-generator-tayra = { workspace = true, editable = true }

[dependency-groups]
dev = [
    "ollama-response-generator-tayra",
]
